FROM nginxinc/nginx-unprivileged:1.28.0-alpine

COPY --chown=101:101 docker/nginx.conf.template /etc/nginx/templates/default.conf.template
COPY --chown=101:101 --chmod=0555 docker/nginx-entrypoint.sh /usr/local/bin/eclipcity-nginx-entrypoint

EXPOSE 8080 8443

ENTRYPOINT ["/usr/local/bin/eclipcity-nginx-entrypoint"]
